package com.hiaashuu.gfxtool.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4359A9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF535F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD7E3F7)
val md_theme_light_onSecondaryContainer = Color(0xFF101C2B)
val md_theme_light_tertiary = Color(0xFF6B5778)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF3DAFF)
val md_theme_light_onTertiaryContainer = Color(0xFF251431)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFBFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFBFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF73777F)
val md_theme_light_outlineVariant = Color(0xFFC3C7CF)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inversePrimary = Color(0xFFB4C5FF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB4C5FF)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF2C4190)
val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_secondary = Color(0xFFBBC7DB)
val md_theme_dark_onSecondary = Color(0xFF253140)
val md_theme_dark_secondaryContainer = Color(0xFF3B4858)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7E3F7)
val md_theme_dark_tertiary = Color(0xFFD7BEE4)
val md_theme_dark_onTertiary = Color(0xFF3B2948)
val md_theme_dark_tertiaryContainer = Color(0xFF523F5F)
val md_theme_dark_onTertiaryContainer = Color(0xFFF3DAFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF121524)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF181E34)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF2C2F45)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C7CF)
val md_theme_dark_outline = Color(0xFF8D9199)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inverseOnSurface = Color(0xFF2F3033)
val md_theme_dark_inversePrimary = Color(0xFF4359A9)
val md_theme_dark_scrim = Color(0xFF000000)

val SuccessGreen = Color(0xFF4CAF50)
val WarningOrange = Color(0xFFFF9800)
val InfoBlue = Color(0xFF2196F3)
val PremiumGold = Color(0xFFFFC857)
val CardDark = Color(0xFF1E243B)
val DividerDark = Color(0xFF2F354D)

val DarkBackground = Color(0xFF0A0A0F)
val DarkSurface = Color(0xFF12121C)
val DarkSurfaceVariant = Color(0xFF1C1C2E)
val NeonPurple = Color(0xFF7C4DFF)
val NeonCyan = Color(0xFF00E5FF)
val NeonOrange = Color(0xFFFF6D00)
val GlowPurple = Color(0x337C4DFF)
val GlowCyan = Color(0x3300E5FF)

val PubgGold = Color(0xFFD4A017)
val PubgOlive = Color(0xFF4A5C2A)
val PubgGoldGlow = Color(0x33D4A017)

val BgmiBlue = Color(0xFF1565C0)
val BgmiOrange = Color(0xFFFF6B00)
val BgmiBlueGlow = Color(0x331565C0)

val FreeFireOrange = Color(0xFFFF4500)
val FreeFireGold = Color(0xFFFFD700)
val FreeFireOrangeGlow = Color(0x33FF4500)

val FreeFireMaxRed = Color(0xFFFF1744)
val FreeFireMaxAmber = Color(0xFFFFD740)
val FreeFireMaxRedGlow = Color(0x33FF1744)

val CodGreen = Color(0xFF00C853)
val CodDarkAccent = Color(0xFF263238)
val CodGreenGlow = Color(0x3300C853)